# Generated by Django 5.1.1 on 2024-09-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=150)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=20)),
                ('message', models.TextField()),
            ],
        ),
    ]
